version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install -f

  build:
    commands:
      - echo "running the build"
      - export NODE_OPTIONS="--max-old-space-size=3072"
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
      - cp appspec.yml build/
      - cp -r script/ build/

artifacts:
  files:
    - 'build/**/*'

