version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - echo "Build phase - Install dependencies and build the Node.js application"
      - npm cache clean -f
      - npm install --legacy-peer-deps # Install Node.js dependencies
      - npm run build # Build your Node.js application (replace with your actual build command)

artifacts:
  files: # Specify the files to be included in the build artifacts
    - '**/*'
  base-directory: ./ # Set the base directory to the root of your application

cache:
  paths:
    - '/root/.npm' # Cache Node.js dependencies to speed up builds
    - '/root/.cache' # Cache other build dependencies as needed
